# This workflow will auto-version when pull-requests are merged to main.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Version New Release (On Merge from Pull)

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches: 
      - "main"

permissions:
  contents: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  versioning_on_merge:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
